spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:myapp}
    username: ${MYSQL_USER:myuser}
    password: ${MYSQL_PASSWORD:mypassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
